# Numpy
    
![Numpy  logo](https://numpy.org/images/logos/numpy.svg)
    
- prepared by [Jakob Nybo Nissen](https://twitter.com/nybojakob), continued by [Henry Webel](https://twitter.com/Henrywebel)
    
The first half of this Notebook contain a small introduction to `numpy`. If you have seen [the YouTube video](https://www.youtube.com/watch?v=8Mpc9ukltVA) and feel comfortable using [`numpy`](https://numpy.org/), you can skip the introduction and go directly to the [exercises (click here)](#exercises). If you would like a recap, keep reading on.

## Introduction

[`numpy`](https://numpy.org/) is a Python package that provides a new type of object: The `ndarray`. This is an N-dimensional array, i.e. a "list" with any number of dimensions.
`numpy` is one of the most fundamental Python packages. Almost all of scientific Python uses [`numpy`](https://numpy.org/) either directly, or indirectly through another package.

[![Figure 2, Harris et. al. 2020](https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41586-020-2649-2/MediaObjects/41586_2020_2649_Fig2_HTML.png?as=webp)](https://www.nature.com/articles/s41586-020-2649-2/figures/2)

It may not be immediately clear why [`numpy`](https://numpy.org/)'s `ndarrays` are so useful that they are everywhere. Do ALL scientific software really need N-dimensional arrays? As you will learn in these exercises, even for 1-dimensional data that *could* be placed in lists, `ndarrays` are generally useful for their convenience and speed.

### Reference
Harris, C. R., Millman, K. J., van der Walt, S. J., Gommers, R., Virtanen, P., Cournapeau, D., Wieser, E., Taylor, J., Berg, S., Smith, N. J., Kern, R., Picus, M., Hoyer, S., van Kerkwijk, M. H., Brett, M., Haldane, A., del Río, J. F., Wiebe, M., Peterson, P., … Oliphant, T. E. (2020). Array programming with NumPy. Nature, 585(7825), 357–362. https://doi.org/10.1038/s41586-020-2649-2


[![Figure1, Harris et. al. 2020](https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41586-020-2649-2/MediaObjects/41586_2020_2649_Fig1_HTML.png?as=webp)](https://www.nature.com/articles/s41586-020-2649-2/figures/1)

### Outline
Today, first start with 1-dimensionalal `ndarray`s and use some statistical operations on them. Then, we will have a look at multidimensional arrays by using matrices, i.e. 2-dimensional `ndarray`'s.

Let's get started right away and import `numpy`:

In [ ]:
# We can import like this to rename numpy "np"
# and make the name shorter
import numpy as np

In [ ]:
# # You could accces your drive files by connecting your drive storage
# from google.colab import drive
# drive.mount('/content/drive')

## Instantiating (creating) `ndarray`s
We begin with a normal Python list of numbers. *italicized text*

In [ ]:
values = [4, 9, 1, 0, 8, 3, 2, 2, 6, 5, 0]
values

[4, 9, 1, 0, 8, 3, 2, 2, 6, 5, 0]

---
We can create an `ndarray` out of this list:

In [ ]:
array = np.array(values)
print(array)
print(type(array))

[4 9 1 0 8 3 2 2 6 5 0]
<class 'numpy.ndarray'>


You notice the `ndarray` looks a lot like a `list`. You can also construct `ndarrays` from a tuple. 




## Slicing
We can access and assign individual numbers in an `ndarray` like we do with `list`:

In [ ]:
print(array[2])
print(array[2:6])
array[3] = 10
print(array)

1
[1 0 8 3]
[ 4  9  1 10  8  3  2  2  6  5  0]


---
We can also loop over the `ndarray`, reverse it, and so on. The full list of methods you find in the docs of [`numpy.ndarray`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html)

There are two main limitations that `ndarrays` have compared to lists. We cannot use `append` or `pop`, or other operations that *changes* the array _in-place_:

In [ ]:
array.append(3)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

---
There are many other ways to instantiate (i.e. create) `ndarray`s. Here are a few useful ones - you might need them later!

In [ ]:
# Create a vector 10 zeros, default dtype is np.float64
print('np.zeros:', np.zeros(10, dtype=np.int64))

# Create an array of a range, similar to the range object
print('np.arange:', np.arange(3, 15, 2))

# Create vector of 10 floats from 3 to 15 having 9
# evenly spaced elements (linear spacing):
print('np.linspace:', np.linspace(3, 15, 9))

# Create a vector of random numbers in the interval [0.0, 1.0)
print('np.random.random:', np.random.random(5))

# Create 9 random integers from 7 to 18
print('np.random.randint:', np.random.randint(7, 19, size=9))

np.zeros: [0 0 0 0 0 0 0 0 0 0]
np.arange: [ 3  5  7  9 11 13]
np.linspace: [ 3.   4.5  6.   7.5  9.  10.5 12.  13.5 15. ]
np.random.random: [0.43395526 0.26952376 0.56649708 0.98576584 0.02292751]
np.random.randint: [ 9 18  7 18 11 11 13  7 10]


## Data type of arrays (`dtype`)

The second disadvantage is that an `ndarray` can only contain one kind of data at a time, i.e. `float` or `int` etc. The data type is given by the `dtype` field of the array:

In [ ]:
array.dtype

dtype('int32')

---
This array contains `np.int64`, a type representing 64-bit integers. If we try to add a `float` to the array, it will be converted to an `np.int64`, or raise an error if that is not possible.

In [ ]:
# 1.7 can be "converted" by rounding down to 1
# (i.e) removing the fraction part, keeping the interger part 1
array[2] = 1.7
print(array)

# "hello" cannot be converted to an integer
array[2] = "hello"

[ 4  9  1 10  8  3  2  2  6  5  0]


ValueError: invalid literal for int() with base 10: 'hello'

---
There are many possible datatypes - you can read more about them [on this link (click)](https://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html). However, we will only look at a few data types.

When you construct an `ndarray`, `numpy` will try to automatically detect the input data type:

In [ ]:
array = np.array([1, 2, 3])
print(array, array.dtype)

array = np.array([1.0, 2.0, 3])
print(array, array.dtype)

[1 2 3] int32
[1. 2. 3.] float64


---
Be careful when constructing `ndarrays` - for example if you try to construct an `ndarray` from a set object, which is not a list or a tuple, it simply create a 1-element `ndarray` containing the set as its only element, and the datatype will be `object`:

In [ ]:
array = np.array({1,2,3})
print(array, array.dtype)

{1, 2, 3} object


---
You can also manually specify the data type you want. Notice here that it converts `2.5` to `2`:

In [ ]:
np.array([1.0, 2.5, 3.0], dtype=np.int64)

array([1, 2, 3], dtype=int64)

---
And you can convert one numpy array to one with another dtype:

In [ ]:
array = np.array([1, 2, 3])
array.astype(np.float64)

array([1., 2., 3.])

## Vectorized operations

Conveniently, for many operations like `+`, `-`, `*`, `/`, `**` and others apply to each element of an `ndarray` automatically. For example, if you write: `array + 5`, this will add 5 to **every element** in the array. This is termed vectorized operations:

In [ ]:
array = np.array([4, 8, 1, 2, 9, 3, 7])
print(array)
print(array + 5)
print(array * 2)
print(array / 2)
print(array**2)
print(0.4 * array**2 + 1.5 * array - 0.9)

[4 8 1 2 9 3 7]
[ 9 13  6  7 14  8 12]
[ 8 16  2  4 18  6 14]
[2.  4.  0.5 1.  4.5 1.5 3.5]
[16 64  1  4 81  9 49]
[11.5 36.7  1.   3.7 45.   7.2 29.2]


> Think about the difference of what the `+`, `-`, `*`, `/` operators invoke in comparison to `str` or `list` built-in types.

Because these vectorized operations actually execute code written in the programming language C, they are much, much faster than ordinary Python:

In [ ]:
import random

# Create a vector of 1 million random floats in [0.0, 1.0):
python_list = [random.random() for i in range(1000000)]

# Convert the Python list to a Numpy vector
numpy_vector = np.array(python_list)

In [ ]:
%timeit [2*i + 3 for i in python_list]

85.5 ms ± 1.2 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
# On Jacob's computer, this is >200x faster than Python 
# In colab (with the lastest Python version?) this is still ~70x faster
# On my machine it is reduced to a 22x faster
%timeit 2*numpy_vector + 3

3.83 ms ± 351 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


### Masking
Importantly, the comparison operators `>`, `>=`, `<`, `<=`, `==`, `!=` are also vectorized. Since these operators always return a `bool` (i.e. `True` or `False`), the result is an `ndarray` of data type `bool`. For example, we can check whether each element in `array` is greater than 3:

In [ ]:
print(array)
above_3 = array > 3
print(above_3)
print(above_3.dtype)

[4 8 1 2 9 3 7]
[ True  True False False  True False  True]
bool


## Logical indexing
*Logical indexing* refers to indexing an `ndarray` using another `ndarray` of dtype `bool`. This selects every element of the `ndarray` paired with the value `True`: For example:

In [ ]:
array = np.array([1, 4, 6, 5, 0, 2, 9, 10, 0, 2, 7, 5])
print('Array:', array)
nonzero = array != 0
print('Nonzero:', nonzero)

# Now get all elements that are not zero:
# Each element in array gets picked if nonzero is True
array[nonzero]

Array: [ 1  4  6  5  0  2  9 10  0  2  7  5]
Nonzero: [ True  True  True  True False  True  True  True False  True  True  True]


array([ 1,  4,  6,  5,  2,  9, 10,  2,  7,  5])

---
You can also assign to an `ndarray` using logical indexing. This will change all the numbers where the boolean array is `True`:

In [ ]:
array[nonzero] = 1
print(array)

[1 1 1 1 0 1 1 1 0 1 1 1]


## `ndarray` methods

In addition to the vectorized opertaions, the `ndarray` object also have some methods (i.e. functions of the object type or class `ndarray`) to conveniently perform operations on the arrays. Like vectorized operations, these methods are very fast. The full list of methods you find in the docs of [`numpy.ndarray`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html).

In [ ]:
array = np.array([4, 8, 1, 2, 9, 3, 7])
print("Our array:", array)
print("Calculate sum:", array.sum())
print("Calculate mean:", array.mean())
print("Calculate variance:", array.var())
print("Calculate standard deviation:", array.std())
print("Calculate minimum/maximum:", array.min(), array.max())

Our array: [4 8 1 2 9 3 7]
Calculate sum: 34
Calculate mean: 4.857142857142857
Calculate variance: 8.408163265306122
Calculate standard deviation: 2.8996833043120627
Calculate minimum/maximum: 1 9


---
Additional functions are not implemented as methods of `ndarray`, but can be found by typing `np.FUNCITON_NAME` such as:

```python
np.log
np.sqrt
np.any
np.all,
```
and many, many more. In general, basic math operations, statistical operations and linear algebra is implemented in Numpy. Any other kind of number-crunching operation you might possibly need can be found in Scipy.


In [ ]:
 print(np.log(array))

[1.38629436 2.07944154 0.         0.69314718 2.19722458 1.09861229
 1.94591015]


# Exercises

In all of these exercises, do not loop over the `ndarray`s you create. All exercises can be solved using only vectorized operations on your arrays.

## Simple vectorized operations

You want to plot the mathematical function

$f(x) = log(-1.3x^2 + 1.4^x + 7x + 50)$

For the numbers in $[0, 20]$. To do this, you need to create a vector `xs` with lots of numbers between 0 and 20, and a vector `ys` with $f$ evaluated at every element of `xs`.

To get a hang of vectorized operations, solve the problem *without using any loops*:

### Create a vector `xs` with 1000 evenly spaced points between 0 and 20

### Create a Python function $f$ as seen above

### Evaluate `ys` = $f(x)$, i.e. $f$ of every element of `xs`.

### What is the mean and standard deviation of `ys`?

### How many elements of. `ys` are below 0? Between 1 and 2, both exclusive?

> Hint: You can use a comparison operator to get an array of dtype `bool`. To get the number of elements that are `True`, you can exploit the fact that `True` behaves similar to the number 1, and `False` similar to the number 0.

### What is the minimum and maximum value of `ys`?

### Create a vector `non_negatives`, which contain all the values of `ys` that are nonnegative.

### _Bonus exercise, not graded:_ Use `matplotlib` to plot `xs` vs `ys`.

## Species matrix

Load in the data `depths.csv`. As seen below, this is a numerical matrix. There are 11 columns, with columns 2-11 representing a sample from a human git microbiome. Each row represents a genome of a micro-organism, a so-called "operational taxonomic unit at 97% sequence identity" (OTU_97). The first row gives the name of the genome. The values in the matrix represents the relative abundance (or depth) of that micro-organism in that sample, i.e. how much of the micro-organism there is.

In [ ]:
# You can use Bash commands by prepending them with !, this function works
# on my computer because I have the correct path to the file depths.csv
from pathlib import Path
filepath = Path('data/depths.csv')

### Load in the matrix in some data structure of your choice, but make sure the numbers in each row is an `ndarray`.

### How many OTUs are there? Show how you figured it out.

### Find the OTU "OTU_97.41189.0". What is the mean and standard deviations of the depths across the 10 samples of this OTU?

### How many samples have 0 depth of that OTU? (or rather, below detection limit?)

### What is the mean and standard deviation if you exclude those samples?

### We are not interested in OTUs present in fewer than 4 samples. Remove all those OTUs.

### How many OTUs did you remove?

### How many OTUs have a depth of > 5 in all 10 samples? (hint: `np.all`)

### Filtering and Normalization

After discarding all OTUs present in fewer than 4 samples, sort the OTUs, do the following:
 - Calculate the mean depth across samples for each remaining OTU.
 - Normalize the remaining OTUs such that each row sum to 0 and have a standard deviation of 1 (so-called z-score normalization)
 - Print the remaining OTUs to a new file in descending order by their mean depth, with a 12th column giving the mean depth, and columns 1-11 being the normalized depth. Make sure that your file looks like the input file (except with the 12th column)

##  Optional exercise: Sequence data as an array
_This exercise will not be graded - only do it if you have extra time._

### load data 

Create a function that loads a FASTA file into a `dict` where each key is the FASTA header and the value is an  `ndarray` corresponding to the sequence. Remember that you need to instantiate `ndarray` from a list, not a string. Test it using the `Yersinia pestis` fasta file from the earlier lesson. You can verify that your `ndarray` has the correct length by checking the `.size` attribute:
  
`array.size`

### Check data
Make your function verify that there are only 'A', 'C', 'G', 'T' and 'N' in the sequence. Convert lowercase letters to uppercase letters.

### GC count
Create a function that calculates GC content of your `ndarray` representing a DNA sequence - ignore Ns. Remember to still use vectorized operations.

### Profile
Use the Jupyter `%timeit` functionality to compare the time spent in your vectorized GC-content function with the GC-content function you created in exercise 2 last monday. See the use of `%timeit` in this Notebook for an example.

## Optional: Sequence data as an array (redo week 1 briefly in numpy)

1. Create a function that loads a FASTA file into a dict where each key is the FASTA header and the value is an ndarray corresponding to the sequence. Remember that you need to instantiate ndarray from a list, not a string. Test it using the Yersinia pestis fasta file from the earlier lesson. You can verify that your ndarray has the correct length by checking the .size attribute of the ndarray.

2. Make your function verify that there are only 'A', 'C', 'G', 'T' and 'N' in the sequence. Convert lowercase letters to uppercase letters.

3. Create a function that calculates GC content of your ndarray representing a DNA sequence - ignore Ns. Remember to still use vectorized operations

4. Use the Jupyter %timeit functionality to compare the time spent in your vectorized GC-content function with the GC-content function you created in exercise 2 last monday. See the use of %timeit in the Notebook for an example.


---
__Congratulations, you finished today's exercise!__